import { connect, disconnect } from 'mongoose'
import Product from '../models/productModel'

const products = [
  // 8 sản phẩm mới
  {
    id: 'p1',
    name: 'iPhone 15 Pro',
    category: 'Điện thoại',
    price: 29990000,
    stock: 50,
    sold: 10,
    rating: 4.8,
    ratingCount: 120,
    isNew: true,
    isBestSeller: false,
    images: ['iphone15pro.jpg'],
    createdAt: new Date(),
    tags: ['Apple', 'Flagship']
  },
  {
    id: 'p2',
    name: 'Samsung Galaxy S24',
    category: 'Điện thoại',
    price: 25990000,
    stock: 40,
    sold: 8,
    rating: 4.7,
    ratingCount: 90,
    isNew: true,
    isBestSeller: false,
    images: ['galaxys24.jpg'],
    createdAt: new Date(),
    tags: ['Samsung', 'Flagship']
  },
  {
    id: 'p3',
    name: 'MacBook Air M3',
    category: 'Laptop',
    price: 32990000,
    stock: 30,
    sold: 5,
    rating: 4.9,
    ratingCount: 60,
    isNew: true,
    isBestSeller: false,
    images: ['mbairm3.jpg'],
    createdAt: new Date(),
    tags: ['Apple', 'Laptop']
  },
  {
    id: 'p4',
    name: 'Dell XPS 13',
    category: 'Laptop',
    price: 27990000,
    stock: 25,
    sold: 7,
    rating: 4.6,
    ratingCount: 50,
    isNew: true,
    isBestSeller: false,
    images: ['dellxps13.jpg'],
    createdAt: new Date(),
    tags: ['Dell', 'Laptop']
  },
  {
    id: 'p5',
    name: 'Sony WH-1000XM5',
    category: 'Tai nghe',
    price: 7990000,
    stock: 60,
    sold: 12,
    rating: 4.8,
    ratingCount: 80,
    isNew: true,
    isBestSeller: false,
    images: ['sonywh1000xm5.jpg'],
    createdAt: new Date(),
    tags: ['Sony', 'Tai nghe']
  },
  {
    id: 'p6',
    name: 'Apple Watch Series 9',
    category: 'Đồng hồ',
    price: 11990000,
    stock: 35,
    sold: 6,
    rating: 4.7,
    ratingCount: 40,
    isNew: true,
    isBestSeller: false,
    images: ['awatch9.jpg'],
    createdAt: new Date(),
    tags: ['Apple', 'Đồng hồ']
  },
  {
    id: 'p7',
    name: 'JBL Flip 6',
    category: 'Loa',
    price: 2990000,
    stock: 70,
    sold: 9,
    rating: 4.5,
    ratingCount: 30,
    isNew: true,
    isBestSeller: false,
    images: ['jblflip6.jpg'],
    createdAt: new Date(),
    tags: ['JBL', 'Loa']
  },
  {
    id: 'p8',
    name: 'Canon EOS R10',
    category: 'Máy ảnh',
    price: 19990000,
    stock: 20,
    sold: 4,
    rating: 4.6,
    ratingCount: 25,
    isNew: true,
    isBestSeller: false,
    images: ['canoneosr10.jpg'],
    createdAt: new Date(),
    tags: ['Canon', 'Máy ảnh']
  },
  // 6 sản phẩm bán chạy
  {
    id: 'p9',
    name: 'Xiaomi Redmi Note 12',
    category: 'Điện thoại',
    price: 5990000,
    stock: 100,
    sold: 80,
    rating: 4.4,
    ratingCount: 200,
    isNew: false,
    isBestSeller: true,
    images: ['redminote12.jpg'],
    createdAt: new Date(),
    tags: ['Xiaomi', 'Bán chạy']
  },
  {
    id: 'p10',
    name: 'Oppo Reno8',
    category: 'Điện thoại',
    price: 7990000,
    stock: 90,
    sold: 70,
    rating: 4.3,
    ratingCount: 180,
    isNew: false,
    isBestSeller: true,
    images: ['opporeno8.jpg'],
    createdAt: new Date(),
    tags: ['Oppo', 'Bán chạy']
  },
  {
    id: 'p11',
    name: 'HP Pavilion 15',
    category: 'Laptop',
    price: 15990000,
    stock: 60,
    sold: 65,
    rating: 4.2,
    ratingCount: 150,
    isNew: false,
    isBestSeller: true,
    images: ['hppavilion15.jpg'],
    createdAt: new Date(),
    tags: ['HP', 'Bán chạy']
  },
  {
    id: 'p12',
    name: 'Logitech MX Master 3',
    category: 'Chuột',
    price: 2490000,
    stock: 80,
    sold: 60,
    rating: 4.7,
    ratingCount: 140,
    isNew: false,
    isBestSeller: true,
    images: ['mxmaster3.jpg'],
    createdAt: new Date(),
    tags: ['Logitech', 'Bán chạy']
  },
  {
    id: 'p13',
    name: 'Samsung Galaxy Buds2',
    category: 'Tai nghe',
    price: 3990000,
    stock: 70,
    sold: 55,
    rating: 4.5,
    ratingCount: 130,
    isNew: false,
    isBestSeller: true,
    images: ['galaxybuds2.jpg'],
    createdAt: new Date(),
    tags: ['Samsung', 'Bán chạy']
  },
  {
    id: 'p14',
    name: 'Asus ROG Strix G15',
    category: 'Laptop',
    price: 24990000,
    stock: 40,
    sold: 50,
    rating: 4.6,
    ratingCount: 120,
    isNew: false,
    isBestSeller: true,
    images: ['rogstrixg15.jpg'],
    createdAt: new Date(),
    tags: ['Asus', 'Bán chạy']
  },
  // 8 sản phẩm xem nhiều nhất
  {
    id: 'p15',
    name: 'Google Pixel 8',
    category: 'Điện thoại',
    price: 20990000,
    stock: 30,
    sold: 15,
    rating: 4.9,
    ratingCount: 300,
    isNew: false,
    isBestSeller: false,
    images: ['pixel8.jpg'],
    createdAt: new Date(),
    tags: ['Google', 'Xem nhiều']
  },
  {
    id: 'p16',
    name: 'Lenovo ThinkPad X1',
    category: 'Laptop',
    price: 34990000,
    stock: 20,
    sold: 10,
    rating: 4.8,
    ratingCount: 250,
    isNew: false,
    isBestSeller: false,
    images: ['thinkpadx1.jpg'],
    createdAt: new Date(),
    tags: ['Lenovo', 'Xem nhiều']
  },
  {
    id: 'p17',
    name: 'Sony Alpha A7 IV',
    category: 'Máy ảnh',
    price: 49990000,
    stock: 10,
    sold: 5,
    rating: 4.7,
    ratingCount: 220,
    isNew: false,
    isBestSeller: false,
    images: ['alphaa7iv.jpg'],
    createdAt: new Date(),
    tags: ['Sony', 'Xem nhiều']
  },
  {
    id: 'p18',
    name: 'Apple iPad Pro M2',
    category: 'Tablet',
    price: 27990000,
    stock: 25,
    sold: 8,
    rating: 4.8,
    ratingCount: 210,
    isNew: false,
    isBestSeller: false,
    images: ['ipadprom2.jpg'],
    createdAt: new Date(),
    tags: ['Apple', 'Xem nhiều']
  },
  {
    id: 'p19',
    name: 'Bose QuietComfort 45',
    category: 'Tai nghe',
    price: 8990000,
    stock: 40,
    sold: 12,
    rating: 4.6,
    ratingCount: 180,
    isNew: false,
    isBestSeller: false,
    images: ['boseqc45.jpg'],
    createdAt: new Date(),
    tags: ['Bose', 'Xem nhiều']
  },
  {
    id: 'p20',
    name: 'MSI Modern 14',
    category: 'Laptop',
    price: 13990000,
    stock: 50,
    sold: 7,
    rating: 4.5,
    ratingCount: 160,
    isNew: false,
    isBestSeller: false,
    images: ['msimodern14.jpg'],
    createdAt: new Date(),
    tags: ['MSI', 'Xem nhiều']
  }
]

async function seed() {
  await connect('mongodb://localhost:27017/zalo-visa-red')
  await Product.deleteMany({})
  await Product.insertMany(products)
  console.log('Seeded 20 products!')
  disconnect()
}

seed()
